### ISSUE TITLE
Failed to connect to Hub

### ISSUE THREAD

**Issue by 5MarsR** [iot-for-all/iotc-python-client#3] opened 2021-06-18 16:46 UTC
Hi, 

I'm using python 3.9
on Linux

I tried using the async_device_key example and it seems there is a problem with the client.connect() every time i start the code i get:
`Device connected
Current twin: {'desired': {'prop': 50, '$version': 7}, 'reported': {'writeableProp': 50, '$version': 10}}
ERROR: Failed to connect to Hub` 

it seems the problems comes from this line:
- twin_patch = self._sync_twin()

if i comment it the code runs normaly

**Comment by lucadruda** [comment] 2021-06-21 13:56
Can't reproduce with Python 3.8. Tried with 3.9 and have a different error. I'm trying to see if it's related.

**Comment by 5MarsR** [comment] 2021-06-22 03:07
Weird, 

because every time I try to run the code without the line commented I get disconnected.

**Comment by lucadruda** [comment] 2021-06-22 07:20
can you provide more details on environment and credential type?

**Comment by 5MarsR** [comment] 2021-06-22 13:25
I tried in the visual studio code environment both on Linux and windows, I also tried on a raspberry pi running raspbian directly from the system terminal. I'm using the device key credentials to connect.

**Comment by 5MarsR** [comment] 2021-06-22 20:39
okay thank you, I will take a look

**Comment by firedog1024** [comment] 2021-06-22 20:40
@5MarsR  I was able to repro the issue here and as you suspected the problem is due to how we are processing the desired properties in the device twin.  We made a change in a one of our releases some time ago to align our twin structure with that of the IoT Hub, and as such we removed the JSON object wrapping around desired properties.  It appears that we did not change the IOTC SDK to accommodate that change and it is still expecting there to be an object wrapper around the desired property and that is causing the exception.  I chatted with @lucadruda and we need to make some fairly extensive repairs in this code to fix up a number of issues to keep pace with changes in IoT Central and it's going to take a while.  I'm going to make a simple fix for this specific issue but will not check it into the main branch as it's really a Band-Aid fix and not something I want to push to pypi.  Once I have a fix in a branch I'll update the issue thread here so you can pull the library from that branch or patch your current copy.  

I have to stress that if you are starting new development of a python IoT project I would advise using the official Azure IoT Python device SDK.  This project was built when there was not a native python SDK for Azure IoT (it was a python wrapper on the C SDK) and some of our users needed a native python SDK for IoT Central.  The official Python SDK is very stable and is fully funded by Azure so it is under constant development and maintenance.  This is the SDK that most of our samples are written in today.  The SDK can be found here https://github.com/Azure/azure-iot-sdk-python

**Comment by firedog1024** [comment] 2021-06-23 03:32
@5MarsR if you want to continue using this to connect your python code to IoT Central I made a couple of small fixes to the code so you should no longer see the disconnect issue and the desired properties should now be handled correctly.  I made the change in this branch https://github.com/iot-for-all/iotc-python-client/tree/quickfix and the pull request can be seen here to see the exact fix I applied https://github.com/iot-for-all/iotc-python-client/pull/4.  @lucadruda is going to take a closer look at this code when he returns from vacation and make a more substantial fix for a this and a number of other areas that need attention.  Sorry for the inconvenience of this and hopefully this fix helps

**Comment by 5MarsR** [comment] 2021-06-23 15:00
thank you, I will try it this weekend

**Comment by lucadruda** [comment] 2021-06-25 16:28
fixes are applied on #5.
Advise is always to use official SDK for new developments of course

**Comment by lucadruda** [comment] 2021-06-28 09:14
@5MarsR please let us know if your issue is fixed so we can close this

**Comment by 5MarsR** [comment] 2021-06-28 12:56
I will take a look as soon has I can, I should test it during the next few days.

**Comment by 5MarsR** [comment] 2021-07-03 15:26
seems all is working fine for me, thanks a lot for the support

**Comment by lucadruda** [comment] 2021-07-05 09:33
closing as issue got fixed in 1.1.1

**Closed by lucadruda** 2021-07-05 09:33 UTC
